name: NEW_config_v3 Auto Update

permissions:
 contents: write

on:
  schedule:
    - cron: '0 */3 * * *'   # каждые 3 часа (00:00, 03:00, 06:00, 09:00... UTC)
  workflow_dispatch:        # чтобы можно было запускать вручную

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install requests
        run: python main.py
          python -m pip install --upgrade pip
          pip install requests

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update NEW_config_v3 config"
          # ВОТ ТУТ ДОЛЖНО СТОЯТЬ НАЗВАНИЕ:
          file_pattern: 'NEW_config_v3.txt'
