name: Auto Update Configs V2

permissions:
  contents: write

on:
  schedule:
    - cron: '15 */4 * * *'   # Сдвинули время (раз в 4 часа, в 15 минут)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python scripts2/update_configs.py

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update system metrics ${{ github.run_number }}" # Нейтральное сообщение
          file_pattern: 'configs_v2.txt sub_v2.txt version_v2.txt'
          skip_dirty_check: true
          commit_author_name: github-actions[bot]
          commit_author_email: github-actions[bot]@users.noreply.github.com
