name: NEW_config_v3 Auto Update

permissions:
  contents: write

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch: # Чтобы можно было запустить вручную для проверки

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python update.yml # ПРОВЕРЬ: если файл Main.py с большой, исправь тут на большую

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update configs"
          file_pattern: 'NEW_config_v3.txt'
